### ISSUE TITLE
Overfitting

### ISSUE THREAD

**Issue by axel578** [losttech/Torch.MinGPT#1]
I have a dataset with 10 000 lines of text.

The data inside is code and is in this format:

nameofskill:
  Skills:
  - effect:particles{etc=random} @target

the first line changes depending on the name of the skill, 
the second line never changes.
The third line changes and is different for each different skill.

The issue is that when I train the model, whatever is the name of the skill, the following lines after the Skills line are always the same.

for example:

fireskill:
  Skills:
  - flame

waterskill:
  Skills:
  - flame

rockskill:
  Skills:
  - flame

it doesnt seems to undertsand what is written ,and changing the temperature to 0.7 does nothing to help. It always output the same data.

**Comment by lostmsu** [comment]
This is a bug tracker for minGPT. The behavior is a bug in your application of minGPT. minGPT works as designed here.
